import { mkdirSync, writeFileSync } from 'fs'
import { join } from 'path'
import ora from 'ora'
import { getAddress, isAddress } from 'viem'
import { resolveContract } from '../core/resolver.js'
import { c } from '../output/colors.js'
import type { AbiInput, AbiItem, Config } from '../types.js'

function validateAddress(raw: string): string {
  if (!isAddress(raw)) throw new Error(`Invalid EVM address: ${raw}`)
  return getAddress(raw)
}

function contractIdentifier(name: string): string {
  const clean = name.replace(/[^A-Za-z0-9_]/g, '') || 'Contract'
  return /^[A-Za-z_]/.test(clean) ? clean : `Contract${clean}`
}

function inputType(input: AbiInput): string {
  if (input.type === 'tuple' && input.components) {
    return `struct /* ${input.components.map(cmp => `${inputType(cmp)} ${cmp.name || '_'}`).join(', ')} */`
  }
  return input.type
}

function param(input: AbiInput, index: number): string {
  return `${inputType(input)} ${input.name || `arg${index}`}`
}

function returns(outputs?: AbiInput[]): string {
  if (!outputs || outputs.length === 0) return ''
  return ` returns (${outputs.map((output, index) => param(output, index)).join(', ')})`
}

function mutability(item: AbiItem): string {
  if (item.stateMutability === 'view' || item.stateMutability === 'pure') return item.stateMutability
  if (item.stateMutability === 'payable') return 'payable'
  return ''
}

function functionLine(item: AbiItem): string | null {
  if (item.type !== 'function' || !item.name) return null
  const args = (item.inputs || []).map(param).join(', ')
  const state = mutability(item)
  return `    function ${item.name}(${args}) external${state ? ` ${state}` : ''}${returns(item.outputs)};`
}

function foundrySource(name: string, address: string, chainName: string, abi: AbiItem[]): string {
  const id = contractIdentifier(name)
  const iface = `I${id}`
  const fnLines = abi.map(functionLine).filter((line): line is string => Boolean(line))
  const hasTotalSupply = abi.some(item => item.type === 'function' && item.name === 'totalSupply' && (item.inputs?.length || 0) === 0)

  return `// SPDX-License-Identifier: MIT
// Auto-generated by unfold v0.1.0
// unfold ${address} --chain ${chainName} --export foundry

pragma solidity ^0.8.19;

import {Test} from "forge-std/Test.sol";

interface ${iface} {
${fnLines.join('\n')}
}

contract ${id}Test is Test {
    ${iface} public target;

    function setUp() public {
        vm.createSelectFork(vm.envString("${chainName.toUpperCase()}_RPC_URL"));
        target = ${iface}(${address});
    }

    function test_example() public view {
${hasTotalSupply ? '        assertGt(target.totalSupply(), 0);' : '        assertTrue(address(target).code.length > 0);'}
    }
}
`
}

export async function runExport(
  rawAddress: string,
  format: string,
  chainName: string,
  config: Config,
  jsonOutput = false
): Promise<void> {
  const address = validateAddress(rawAddress)
  const spinner = jsonOutput ? null : ora({ text: `  Exporting ${format}...`, spinner: 'dots' }).start()

  try {
    const contract = await resolveContract(address, chainName, config)
    const abi = contract.abi || []
    const name = contractIdentifier(contract.name)

    let path: string
    if (format === 'foundry') {
      mkdirSync('test', { recursive: true })
      path = join('test', `${name}.t.sol`)
      writeFileSync(path, foundrySource(name, address, chainName, abi), 'utf-8')
    } else if (format === 'abi') {
      path = `${name}.abi.json`
      writeFileSync(path, JSON.stringify(abi, null, 2), 'utf-8')
    } else if (format === 'json') {
      path = `${name}.unfold.json`
      writeFileSync(path, JSON.stringify(contract, null, 2), 'utf-8')
    } else {
      throw new Error(`Unsupported export format: ${format}. Use foundry, abi, or json.`)
    }

    spinner?.stop()
    if (jsonOutput) {
      console.log(JSON.stringify({ path, format, contract: contract.name }, null, 2))
      return
    }

    console.log()
    console.log(`  ${c.success('✓')} exported ${format} to ${c.address(path)}`)
    console.log()
  } catch (err) {
    spinner?.fail()
    console.error(`\n  ${c.danger('Error:')} ${(err as Error).message}\n`)
    process.exit(1)
  }
}
